name: Validate and sync schema
description: Validate and sync schema values to CCC
author: Extenda Retail
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication
      to the secrets manager.
    required: false # TODO: Change to true
  schema-files:
    description: |
      String of files to be validated and synced, delimited by a `;`.
    required: true
  dry-run:
    description: |
      If 'true', action will only validate.
    required: false
    default: "false"
runs:
  using: node20
  main: index.js
